language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local

env:
  RUN_WITH_COVERAGE=false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  include:
    - php: 5.6
      env:
       - EXECUTE_CS_CHECK=true
       - RUN_WITH_COVERAGE=true
       - PATH="$HOME/.local/bin:$PATH"

  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - travis_retry composer self-update
  - git config --global user.name travis-ci
  - git config --global user.email travis@webproject.xyz
  - if [[ $RUN_WITH_COVERAGE == 'true' ]]; then echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0 ; fi

install:
  - travis_retry composer update --no-interaction --ignore-platform-reqs
  - phpunit --version

script:
  - if [[ $RUN_WITH_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.xml ; fi
  - if [[ $RUN_WITH_COVERAGE != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - if [[ $RUN_WITH_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash) ; fi
  - if [[ $RUN_WITH_COVERAGE == 'true' ]]; then ./vendor/bin/test-reporter --coverage-report=coverage.xml ; fi

notifications:
  email: false
